- name: trigger
  hosts: localhost
  vars:
    Uname: "admin"
    Pass: "admin"
    HostName: "3.93.187.246:8080"
    TokenName: "111096e7f1d32d20ef089bd89fe047f3e6"
  tasks:
  - name: Queue build
    uri:
      url: "http://{{ HostName }}/job/{{ JobName }}/build?token={{ TokenName }}"
      method: POST
      user: "{{ Uname }}"
      password: "{{ Pass }}"
      force_basic_auth: yes
      status_code: 201
